import { runFireSimulation } from './src/calculators/fire/index.js';
import { DEFAULT_FIRE_INPUTS } from './src/defaultInputs.js';
import { marriageEventHandler } from './src/features/fire/events/handlers/marriageEventHandler.js';
import { initializeLifePlanIfMissing, deriveLegacyInputsFromLifePlan } from './src/models/lifePlan/lifePlanNormalization.js';
import { getSaveUpdates } from './src/components/fire-simulator/life-profile/lifeProfileSaveAdapter.js';

function deepCompare(a, b, path = '') {
  if (a === b) return;
  if (typeof a !== 'object' || typeof b !== 'object' || a === null || b === null) {
    console.log(`Divergence at ${path}: A = ${JSON.stringify(a)}, B = ${JSON.stringify(b)}`);
    return;
  }
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  for (const k of keys) {
    if (k === 'id' || k === 'objectId' || k === 'metadata' || k === 'createdFromEventId' || k === 'relationshipId' || k === 'partnerId') {
      continue; // Skip autogenerated IDs & metadata per user requirements
    }
    deepCompare(a[k], b[k], path ? `${path}.${k}` : k);
  }
}

// 1. Default (Single Baseline)
const inputs = JSON.parse(JSON.stringify(DEFAULT_FIRE_INPUTS));
inputs.currentAge = 35;
inputs.lifeExpectancy = 85;
inputs.targetRetirementAge = 65;
inputs.simpleIncome = 50000;
inputs.simpleExpenses = 42500;
inputs.useLifeProfile = true;

const resDefault = runFireSimulation(inputs);
console.log(`[Default] Retirement Ready Age: ${resDefault.retirementReadyAge}`);

// 2. Add Marriage
const marriageEvent = {
  id: 'marriage-1',
  type: 'marriage',
  enabled: true,
  name: 'Marriage Event',
  age: 35,
  spouseCurrentAge: 35,
  spouseLifeExpectancy: 85,
  spouseIncome: 50000,
  savingsRate: 15,
  combinedSpendingAfterMarriage: 73540,
  livingTogether: true,
  combineFinances: true
};

const firstSave = marriageEventHandler.save(marriageEvent, inputs);
let inputsWithPartner1 = firstSave.updatedInputs;
let lifePlan1 = initializeLifePlanIfMissing(inputsWithPartner1);
inputsWithPartner1.lifePlan = lifePlan1;

let derivedWithPartner1 = deriveLegacyInputsFromLifePlan(lifePlan1, inputsWithPartner1);
let finalInputs1 = { ...inputsWithPartner1, ...derivedWithPartner1 };
const resFirstMarriage = runFireSimulation(finalInputs1);
console.log(`[First Marriage] Retirement Ready Age: ${resFirstMarriage.retirementReadyAge}`);

// 3. Delete Marriage
const cleanObjects = lifePlan1.objects.filter(o => o.id !== 'spouse-partner' && o.type !== 'relationship');
const updatedPlan = {
  ...lifePlan1,
  objects: cleanObjects,
  events: []
};

const deleteUpdates = getSaveUpdates({
  lifePlan: updatedPlan,
  lifeEvents: [],
  householdMembers: []
}, inputsWithPartner1, 15);

const resDelete = runFireSimulation(deleteUpdates);
console.log(`[After Delete] Retirement Ready Age: ${resDelete.retirementReadyAge}`);

// 4. Re-add Marriage
const secondSave = marriageEventHandler.save(marriageEvent, deleteUpdates);
let inputsWithPartner2 = secondSave.updatedInputs;
let lifePlan2 = initializeLifePlanIfMissing(inputsWithPartner2);
inputsWithPartner2.lifePlan = lifePlan2;

let derivedWithPartner2 = deriveLegacyInputsFromLifePlan(lifePlan2, inputsWithPartner2);
let finalInputs2 = { ...inputsWithPartner2, ...derivedWithPartner2 };
const resSecondMarriage = runFireSimulation(finalInputs2);
console.log(`[Second Marriage] Retirement Ready Age: ${resSecondMarriage.retirementReadyAge}`);

console.log('\n--- Comparing Simulation Inputs (First vs Second Marriage) ---');
deepCompare(finalInputs1, finalInputs2);

console.log('\n--- Comparison complete ---');
