import { test, expect } from 'vitest';
import { runFireSimulation } from './src/calculators/fire/index.js';
import { DEFAULT_FIRE_INPUTS } from './src/defaultInputs.js';
import { marriageEventHandler } from './src/features/fire/events/handlers/marriageEventHandler.js';
import { initializeLifePlanIfMissing, deriveLegacyInputsFromLifePlan } from './src/models/lifePlan/lifePlanNormalization.js';
import { getSaveUpdates } from './src/components/fire-simulator/life-profile/lifeProfileSaveAdapter.js';

test('reproduce partner recreation bug', () => {
  const inputs = JSON.parse(JSON.stringify(DEFAULT_FIRE_INPUTS));
  inputs.currentAge = 35;
  inputs.lifeExpectancy = 85;
  inputs.targetRetirementAge = 65;
  inputs.simpleIncome = 50000;
  inputs.simpleExpenses = 42500;
  inputs.savingsRate = 15;
  inputs.displayedSavingsRate = 15;
  inputs.useLifeProfile = true;

  const marriageEvent = {
    id: 'marriage-1',
    type: 'marriage',
    enabled: true,
    name: 'Marriage Event',
    age: 35,
    spouseCurrentAge: 35,
    spouseLifeExpectancy: 85,
    spouseIncome: 50000,
    savingsRate: 15,
    combinedSpendingAfterMarriage: 73540,
    livingTogether: true,
    combineFinances: true
  };

  console.log("inputs savingsRate:", inputs.savingsRate);

  const firstSave = marriageEventHandler.save(marriageEvent, inputs);
  let inputsWithPartner1 = firstSave.updatedInputs;
  console.log("inputsWithPartner1 savingsRate:", inputsWithPartner1.savingsRate);
  let lifePlan1 = initializeLifePlanIfMissing(inputsWithPartner1);
  inputsWithPartner1.lifePlan = lifePlan1;

  let derivedWithPartner1 = deriveLegacyInputsFromLifePlan(lifePlan1, inputsWithPartner1);
  console.log("derivedWithPartner1 savingsRate:", derivedWithPartner1.savingsRate);
  let finalInputs1 = { ...inputsWithPartner1, ...derivedWithPartner1 };
  console.log("finalInputs1 savingsRate:", finalInputs1.savingsRate);
  const resFirstMarriage = runFireSimulation(finalInputs1);
  
  // Delete Marriage
  const cleanObjects = lifePlan1.objects.filter(o => o.id !== 'spouse-partner' && o.type !== 'relationship');
  const updatedPlan = {
    ...lifePlan1,
    objects: cleanObjects,
    events: []
  };

  const deleteUpdates = getSaveUpdates({
    lifePlan: updatedPlan,
    lifeEvents: [],
    householdMembers: []
  }, inputsWithPartner1, 15);
  console.log("deleteUpdates savingsRate:", deleteUpdates.savingsRate);

  // Re-add Marriage
  const secondSave = marriageEventHandler.save(marriageEvent, { ...inputsWithPartner1, ...deleteUpdates });
  let inputsWithPartner2 = secondSave.updatedInputs;
  console.log("inputsWithPartner2 savingsRate:", inputsWithPartner2.savingsRate);
  let lifePlan2 = initializeLifePlanIfMissing(inputsWithPartner2);
  inputsWithPartner2.lifePlan = lifePlan2;

  let derivedWithPartner2 = deriveLegacyInputsFromLifePlan(lifePlan2, inputsWithPartner2);
  console.log("derivedWithPartner2 savingsRate:", derivedWithPartner2.savingsRate);
  let finalInputs2 = { ...inputsWithPartner2, ...derivedWithPartner2 };
  console.log("finalInputs2 savingsRate:", finalInputs2.savingsRate);
  const resSecondMarriage = runFireSimulation(finalInputs2);

  console.log("FIRST MARRIAGE READY AGE:", resFirstMarriage.retirementReadyAge);
  console.log("SECOND MARRIAGE READY AGE:", resSecondMarriage.retirementReadyAge);

  expect(resSecondMarriage.retirementReadyAge).toBe(resFirstMarriage.retirementReadyAge);
  expect(resFirstMarriage.retirementReadyAge).toBe(52);

  console.log("FINAL INPUTS 1 EVENTS:");
  console.log(finalInputs1.lifeEvents.map(e => ({ id: e.id, type: e.type, enabled: e.enabled })));

  console.log("\nFINAL INPUTS 2 EVENTS:");
  console.log(finalInputs2.lifeEvents.map(e => ({ id: e.id, type: e.type, enabled: e.enabled })));

  console.log("\nDELETE UPDATES EVENTS:");
  console.log(deleteUpdates.lifeEvents.map(e => ({ id: e.id, type: e.type, enabled: e.enabled })));

  // Compare key-by-key
  const cleanForCompare = (obj) => {
    const copy = JSON.parse(JSON.stringify(obj));
    // Remove autogenerated IDs or timestamps
    const cleanObj = (val) => {
      if (!val || typeof val !== 'object') return val;
      if (Array.isArray(val)) {
        return val.map(cleanObj).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)));
      }
      const res = {};
      Object.keys(val).forEach(k => {
        if (['id', 'timestamp', 'createdFromEventId', 'relationshipId', 'partnerId', 'objectId', 'activeFromDate'].includes(k)) {
          return;
        }
        res[k] = cleanObj(val[k]);
      });
      return res;
    };
    return cleanObj(copy);
  };

  const c1 = cleanForCompare(finalInputs1);
  const c2 = cleanForCompare(finalInputs2);

  const diffKeys = [];
  Object.keys(c1).forEach(k => {
    if (JSON.stringify(c1[k]) !== JSON.stringify(c2[k])) {
      diffKeys.push(k);
    }
  });
  console.log("DIFFERING KEYS:", diffKeys);
  diffKeys.forEach(k => {
    if (k !== 'lifePlan' && k !== 'objects') {
      console.log(`\nKey: ${k}`);
      console.log("C1:", JSON.stringify(c1[k], null, 2));
      console.log("C2:", JSON.stringify(c2[k], null, 2));
    } else {
      console.log(`\nKey: ${k} differs`);
    }
  });
});
