// @vitest-environment jsdom
import React from 'react';
import { render, screen, cleanup, fireEvent } from '@testing-library/react';
import { describe, test, expect, vi, beforeEach } from 'vitest';
import EventsWorkspace from './src/components/fire-simulator/life-profile/EventsWorkspace';
import { DEFAULT_FIRE_INPUTS } from './src/defaultInputs';

const mockSnapshot = {
  relationshipStatus: 'single',
  housingStatus: 'rent',
  children: [],
  income: { annualIncome: 50000 },
  assets: { investedAssets: 100000 },
  debts: { activeDebts: [] }
};

const mockProjection = {
  years: [],
  upcomingMilestones: [],
  rows: [
    { id: 'assets', items: [] }
  ]
};

describe('EventsWorkspace UI Phase 2D Verification Tests', () => {
  let handleCreateEventMock;
  let handleEditRoadmapEventMock;
  let handleDeleteEventMock;

  beforeEach(() => {
    cleanup();
    handleCreateEventMock = vi.fn();
    handleEditRoadmapEventMock = vi.fn();
    handleDeleteEventMock = vi.fn();
  });

  test('EventsWorkspace lists canonical user-authored life events', () => {
    const customInputs = {
      ...DEFAULT_FIRE_INPUTS,
      currentAge: 35,
      lifeEvents: [
        { id: 'ev-married', type: 'marriage', enabled: true, age: 40, name: 'Get Married' },
        { id: 'ev-buyhouse', type: 'buyHouse', enabled: true, purchaseAge: 45, homePrice: 500000, name: 'Buy Home' }
      ]
    };

    render(
      <EventsWorkspace
        isMobile={false}
        inputs={customInputs}
        projection={mockProjection}
        snapshot={mockSnapshot}
        selectedAge={35}
        currentAge={35}
        lifeExpectancy={85}
        onSelectedAgeChange={() => {}}
        expandedCategories={new Set()}
        setExpandedCategories={() => {}}
        handleCreateEvent={handleCreateEventMock}
        handleEditRoadmapEvent={handleEditRoadmapEventMock}
        handleDeleteEvent={handleDeleteEventMock}
        simulation={{}}
      />
    );

    // Verify canonical events are rendered (using regex to ignore emojis/prefixes/suffixes)
    expect(screen.getAllByText(/Get Married/).length).toBeGreaterThan(0);
    expect(screen.getAllByText(/Buy Home/).length).toBeGreaterThan(0);
    expect(screen.getAllByText(/Age 40/).length).toBeGreaterThan(0);
    expect(screen.getAllByText(/Age 45/).length).toBeGreaterThan(0);
  });

  test('EventsWorkspace ignores derived timeline projection artifacts/milestones', () => {
    // E.g., child support ends (milestone) or mortgage off (milestone) are generated by useTimelineEvents
    // but should not be shown as editable events in canonical list
    const customInputs = {
      ...DEFAULT_FIRE_INPUTS,
      currentAge: 35,
      lifeEvents: [
        { id: 'ev-child-1', type: 'haveChild', enabled: true, birthAge: 38, childName: 'Alex' }
      ]
    };

    // Render workspace
    render(
      <EventsWorkspace
        isMobile={false}
        inputs={customInputs}
        projection={mockProjection}
        snapshot={mockSnapshot}
        selectedAge={35}
        currentAge={35}
        lifeExpectancy={85}
        onSelectedAgeChange={() => {}}
        expandedCategories={new Set()}
        setExpandedCategories={() => {}}
        handleCreateEvent={handleCreateEventMock}
        handleEditRoadmapEvent={handleEditRoadmapEventMock}
        handleDeleteEvent={handleDeleteEventMock}
        simulation={{}}
      />
    );

    // "Have Child: Alex" (original event) should be present
    expect(screen.getAllByText(/Have Child: Alex/).length).toBeGreaterThan(0);

    // "Support for Alex Ends" is a derived milestone phase, and should NOT be listed
    expect(screen.queryByText(/Support for Alex Ends/)).toBeNull();
  });

  test('Unscheduled Events are listed from canonical events with invalid/missing age fields', () => {
    const customInputs = {
      ...DEFAULT_FIRE_INPUTS,
      currentAge: 35,
      lifeEvents: [
        { id: 'ev-custom-unsched', type: 'custom', enabled: true, name: 'Dream Vacation', age: null }
      ]
    };

    render(
      <EventsWorkspace
        isMobile={false}
        inputs={customInputs}
        projection={mockProjection}
        snapshot={mockSnapshot}
        selectedAge={35}
        currentAge={35}
        lifeExpectancy={85}
        onSelectedAgeChange={() => {}}
        expandedCategories={new Set()}
        setExpandedCategories={() => {}}
        handleCreateEvent={handleCreateEventMock}
        handleEditRoadmapEvent={handleEditRoadmapEventMock}
        handleDeleteEvent={handleDeleteEventMock}
        simulation={{}}
      />
    );

    expect(screen.getByText('Dream Vacation')).toBeDefined();
    expect(screen.getAllByText(/Unscheduled/).length).toBeGreaterThan(0);
  });

  test('Clicking Edit and Delete passes the original canonical event object', () => {
    const targetEvent = { id: 'ev-married-target', type: 'marriage', enabled: true, age: 40, name: 'Target Wedding' };
    const customInputs = {
      ...DEFAULT_FIRE_INPUTS,
      currentAge: 35,
      lifeEvents: [targetEvent]
    };

    render(
      <EventsWorkspace
        isMobile={false}
        inputs={customInputs}
        projection={mockProjection}
        snapshot={mockSnapshot}
        selectedAge={35}
        currentAge={35}
        lifeExpectancy={85}
        onSelectedAgeChange={() => {}}
        expandedCategories={new Set()}
        setExpandedCategories={() => {}}
        handleCreateEvent={handleCreateEventMock}
        handleEditRoadmapEvent={handleEditRoadmapEventMock}
        handleDeleteEvent={handleDeleteEventMock}
        simulation={{}}
      />
    );

    // Edit button click
    const editBtn = screen.getByRole('button', { name: 'Edit' });
    fireEvent.click(editBtn);
    expect(handleEditRoadmapEventMock).toHaveBeenCalledWith(targetEvent);

    // Delete button click
    const deleteBtn = screen.getByRole('button', { name: 'Delete' });
    fireEvent.click(deleteBtn);
    expect(handleDeleteEventMock).toHaveBeenCalledWith(targetEvent);
  });
});
