// @vitest-environment jsdom
import { describe, test, expect, beforeEach } from 'vitest';
import { runFireSimulation, getNormalizedPhases, getPhaseChangeExplanations } from './src/fireCalculations.js';
import { DEFAULT_FIRE_INPUTS } from './src/defaultInputs.js';

describe('Life Phases Budgeting', () => {
  let baseInputs;

  beforeEach(() => {
    baseInputs = JSON.parse(JSON.stringify(DEFAULT_FIRE_INPUTS));
    baseInputs.lifeEvents = baseInputs.lifeEvents || [];
    baseInputs.householdMembers = [];
    baseInputs.incomeList = [];
    baseInputs.spendingPhases = [];
    baseInputs.debtList = [];
    baseInputs.currentConditions = [];
  });

  test('Phase boundaries generated by debt starts/payoffs, marriage, childcare, and house purchases', () => {
    baseInputs.currentAge = 30;
    baseInputs.lifeExpectancy = 80;
    baseInputs.targetRetirementAge = 65;

    // Add marriage at age 35
    baseInputs.lifeEvents.push({
      id: 'marriage-1',
      type: 'marriage',
      enabled: true,
      age: 35,
      spouseIncome: 50000,
      savingsRate: 10
    });

    // Add child at age 38 (childcare starts at 38, ends at 38 + 18 = 56)
    baseInputs.lifeEvents.push({
      id: 'child-1',
      type: 'haveChild',
      enabled: true,
      age: 38,
      birthAge: 38
    });

    // Add student loan starting at 30, paying off at 40
    baseInputs.lifeEvents.push({
      id: 'student-loan',
      type: 'borrowing',
      borrowingType: 'studentLoan',
      name: 'Student Loan',
      balance: 12000,
      interestRate: 0,
      minPayment: 100, // pays off in 10 years, i.e., age 40
      startAge: 30,
      isExisting: true,
      enabled: true
    });

    // Add house purchase at age 45
    baseInputs.lifeEvents.push({
      id: 'house-1',
      type: 'buyHouse',
      enabled: true,
      purchaseAge: 45,
      price: 300000,
      downPaymentPercent: 20,
      interestRate: 6.0,
      loanTermYears: 30
    });

    const phases = getNormalizedPhases(baseInputs);

    // Verify boundaries exists for these ages
    const startAges = phases.map(p => p.startAge);
    expect(startAges).toContain(30);
    expect(startAges).toContain(35);
    expect(startAges).toContain(38);
    expect(startAges).toContain(40);
    expect(startAges).toContain(45);
    expect(startAges).toContain(56);
    expect(startAges).toContain(65);
  });

  test('Proper budget inheritance from prior phases (cascading overrides)', () => {
    baseInputs.currentAge = 30;
    baseInputs.lifeExpectancy = 80;
    baseInputs.targetRetirementAge = 65;

    baseInputs.incomeList.push({
      id: 'inc-1',
      name: 'Salary 1',
      amount: 60000,
      frequency: 'yearly',
      startAge: 30,
      endAge: 40,
      growthRate: 0.03,
      isTaxable: true
    });
    baseInputs.incomeList.push({
      id: 'inc-2',
      name: 'Salary 2',
      amount: 100000,
      frequency: 'yearly',
      startAge: 40,
      endAge: 65,
      growthRate: 0.03,
      isTaxable: true
    });

    // Add override in first phase: modify leisure to 500
    baseInputs.budgetDetails = {
      phases: [
        {
          id: 'workSave_30_40',
          type: 'workSave',
          startAge: 30,
          endAge: 40,
          expenses: {
            housing: 1000,
            leisure: 500,
            diningOut: 200
          },
          savings: {
            trad401k: 200
          }
        }
      ]
    };

    const phases = getNormalizedPhases(baseInputs);
    
    // First phase (30-40) should have leisure = 500
    const phase1 = phases.find(p => p.startAge === 30);
    expect(phase1.expenses.leisure).toBe(500);

    // Second phase (40-65) should inherit leisure = 500 from the first phase
    const phase2 = phases.find(p => p.startAge === 40);
    expect(phase2.expenses.leisure).toBe(500);
    expect(phase2.savings.trad401k).toBe(200);
  });

  test('Editing one phase does not modify prior phases', () => {
    baseInputs.currentAge = 30;
    baseInputs.lifeExpectancy = 80;
    baseInputs.targetRetirementAge = 65;

    baseInputs.incomeList.push({
      id: 'inc-1',
      name: 'Salary 1',
      amount: 60000,
      frequency: 'yearly',
      startAge: 30,
      endAge: 40,
      growthRate: 0.03
    });
    baseInputs.incomeList.push({
      id: 'inc-2',
      name: 'Salary 2',
      amount: 100000,
      frequency: 'yearly',
      startAge: 40,
      endAge: 65,
      growthRate: 0.03
    });

    baseInputs.budgetDetails = {
      phases: [
        {
          id: 'workSave_30_40',
          type: 'workSave',
          startAge: 30,
          endAge: 40,
          expenses: {
            housing: 1000,
            leisure: 300
          },
          savings: {}
        },
        {
          id: 'careerChange_40_65',
          type: 'careerChange',
          startAge: 40,
          endAge: 65,
          expenses: {
            housing: 1000,
            leisure: 600
          },
          savings: {}
        }
      ]
    };

    const phases = getNormalizedPhases(baseInputs);
    const phase1 = phases.find(p => p.startAge === 30);
    const phase2 = phases.find(p => p.startAge === 40);

    // Prior phase is untouched (300) while current phase is updated (600)
    expect(phase1.expenses.leisure).toBe(300);
    expect(phase2.expenses.leisure).toBe(600);
  });

  test('Dragging events regenerates phase boundaries and preserves overrides', () => {
    baseInputs.currentAge = 30;
    baseInputs.lifeExpectancy = 80;
    baseInputs.targetRetirementAge = 65;

    const careerChangeEvent = {
      id: 'inc-2',
      name: 'Salary 2',
      amount: 100000,
      frequency: 'yearly',
      startAge: 40,
      endAge: 65,
      growthRate: 0.03
    };
    baseInputs.incomeList.push(careerChangeEvent);

    baseInputs.budgetDetails = {
      phases: [
        {
          id: 'careerChange_40_65',
          type: 'careerChange',
          startAge: 40,
          endAge: 65,
          expenses: {
            housing: 1200,
            leisure: 800
          },
          savings: {}
        }
      ]
    };

    let phases = getNormalizedPhases(baseInputs);
    let careerPhase = phases.find(p => p.type === 'careerChange');
    expect(careerPhase.startAge).toBe(40);
    expect(careerPhase.expenses.leisure).toBe(800);

    careerChangeEvent.startAge = 42;
    baseInputs.incomeList = [careerChangeEvent];

    phases = getNormalizedPhases(baseInputs);
    careerPhase = phases.find(p => p.type === 'careerChange');
    
    expect(careerPhase.startAge).toBe(42);
    expect(careerPhase.expenses.leisure).toBe(800);
  });

  test('Retirement projection updates correctly after phase modifications', () => {
    baseInputs.currentAge = 35;
    baseInputs.targetRetirementAge = 65;
    baseInputs.lifeExpectancy = 85;
    baseInputs.simpleIncome = 100000;
    baseInputs.simpleExpenses = 50000;
    baseInputs.includeTaxes = false;

    const baselineResults = runFireSimulation(baseInputs);
    const baselineAge65Portfolio = baselineResults.nominalData.find(d => d.age === 65).portfolio;

    baseInputs.budgetDetails = {
      phases: [
        {
          id: 'workSave_35_65',
          type: 'workSave',
          startAge: 35,
          endAge: 65,
          expenses: {
            housing: 1000,
            utilities: 200,
            food: 300,
            transportation: 200,
            healthcare: 100,
            leisure: 100,
            diningOut: 100,
            misc: 100
          },
          savings: {
            brokerage: 4000
          }
        }
      ]
    };

    const overrideResults = runFireSimulation(baseInputs);
    const overrideAge65Portfolio = overrideResults.nominalData.find(d => d.age === 65).portfolio;

    expect(overrideAge65Portfolio).toBeGreaterThan(baselineAge65Portfolio);
  });
});
