import {
  getActiveChildrenCountAtAge,
  getSocialSecurityFactor,
  getIncomeHistory,
  calculateSocialSecurityBenefit,
  buildSocialSecurityEarningsRecord,
  calculateAIME,
  calculatePIA,
  calculateClaimingAgeMultiplier,
  calculateTop35AverageIncome,
  validateSocialSecurityClaimAge,
  getProfileFromInputs,
  getEventsFromInputs,
  validateFireInputs,
  getPartitionedPhases,
  derivePhasesFromEvents,
  getNormalizedPhases,
  projectYearlyBalances,
  calculateMinimumPortfolioForRetirement,
  computeRetirementResult,
  getSavingsPriority,
  runFireSimulation
} from './calculators/fire/index.js';

export {
  getActiveChildrenCountAtAge,
  getSocialSecurityFactor,
  getIncomeHistory,
  calculateSocialSecurityBenefit,
  buildSocialSecurityEarningsRecord,
  calculateAIME,
  calculatePIA,
  calculateClaimingAgeMultiplier,
  calculateTop35AverageIncome,
  validateSocialSecurityClaimAge,
  getProfileFromInputs,
  getEventsFromInputs,
  validateFireInputs,
  getPartitionedPhases,
  derivePhasesFromEvents,
  getNormalizedPhases,
  projectYearlyBalances,
  calculateMinimumPortfolioForRetirement,
  computeRetirementResult,
  getSavingsPriority,
  runFireSimulation
};